### ISSUE TITLE
A problem in bandits/bandits/bandit.py

### ISSUE THREAD

**Issue by aqian2006** [bgalbraith/bandits#3]
Thank you very much for the code of n-armed bandits problem.
I read your code, and found there may be a mistake in the file 
bandits/bandits/bandit.py
line 38: return (np.random.normal(self.action_values[action]),

I think the correct one should be the following 
line 38: return (self.action_values[action],

If you use np.random.normal() here, a new random number will be generated with mean self.action_values[action], this is not what we want, right?

**Comment by bgalbraith** [comment]
Hi @aqian2006,

That code is actually correct, as it is specific to the GaussianBandit class, which is designed to return values that are drawn from a set of Gaussian distributions. In this case, self.action_values[action] returns the parameters of the k-th arm's distribution, i.e. mean and standard deviation, which we then use to draw a random sample.

This particular class is used in the Value Estimation Jupyter notebook, which replicates the examples from chapter 2 of Sutton & Barto's "Reinforcement Learning: An Introduction".

Thanks!

**Comment by aqian2006** [comment]
Hi, Byron,

   Thank you very much for your reply. This is Cheng ZHANG@Tokyo, Japan.

>In this case, self.action_values[action] returns the parameters of the k-th arm's distribution, i.e. >mean and standard deviation, which we then use to draw a random sample.

  Now I understand. I misunderstood your code before, I am sorry.

   Actually, I am reading Sutton & Barto's book "Reinforcement Learning: An Introduction". When I was reading n-armed bandit part, I found your code by Google.  It is really helpful, thank you very much!

Best regards

**Comment by aqian2006** [comment]
Hi, Byron,

   Thank you very much for your reply. 

In this case, self.action_values[action] returns the parameters of the k-th arm's distribution, i.e. mean and standard deviation, which we then use to draw a random sample.

   Now I understand. I misunderstood the code before, I am sorry.

   Actually, I am reading Sutton & Barto's book "Reinforcement Learning: An Introduction". When I was reading n-armed bandit part, I found your code by Google, it is really helpful. Thank you very much.
