### ISSUE TITLE
Do not understand the code

### ISSUE THREAD

**Issue by tianzhipengfei** [bgalbraith/bandits#7]
I see your policy in bandits/agent.py

```
class EpsilonGreedyPolicy(Policy):
    """
    The Epsilon-Greedy policy will choose a random action with probability
    epsilon and take the best apparent approach with probability 1-epsilon. If
    multiple actions are tied for best choice, then a random action from that
    subset is selected.
    """
    def __init__(self, epsilon):
        self.epsilon = epsilon

    def __str__(self):
        return '\u03B5-greedy (\u03B5={})'.format(self.epsilon)

    def choose(self, agent):
        if np.random.random() < self.epsilon:
            return np.random.choice(len(agent.value_estimates))
        else:
            action = np.argmax(agent.value_estimates)
            check = np.where(agent.value_estimates == action)[0]
            if len(check) == 0:
                return action
            else:
                return np.random.choice(check)

```

I do not understand what check means. Action is the biggest element's  indices in the array. And what check means? Also what does its length indicate?

Thank you~

**Comment by Naereen** [comment]
It's easy: `check` will be the list of indexes where `value_estimates` is equal to its maximum.
If there is only one maximum value, `check` is one value, and otherwise, a random action among the one maximizing the values.

But I think there is a bug in this code, the `np.where(...)` should be with `np.where(values == np.max(values))[0]`…

**Comment by Naereen** [comment]
Please note that this package is quite tiny and not so battle tested, I would recommend you to check out [SMPyBandits](https://github.com/SMPyBandits/SMPyBandits/).

**Comment by tianzhipengfei** [comment]
Thank you very much.

**Comment by bgalbraith** [comment]
Thanks for answering @Naereen! Your SMPyBandits project looks quite interesting.
