### ISSUE TITLE
epsilon-greedy choose function may be wrong

### ISSUE THREAD

**Issue by emiliocuestaf** [bgalbraith/bandits#9]
```
class EpsilonGreedyPolicy(Policy):
    [................................]

    def choose(self, agent):
        if np.random.random() < self.epsilon:
            return np.random.choice(len(agent.value_estimates))
        else:
            action = np.argmax(agent.value_estimates)                    <---------
            check = np.where(agent.value_estimates == action)[0]   <------
            if len(check) == 0:
                return action
            else:
                return np.random.choice(check)

```

I don't really get how the lines with "<-----------" work. Action is an index of value_estimates, okay, but in the second line I think you are comparing an index with value_estimates values!! This is the reason why len(check) can be 0. I believe the correct code would be:
```

def choose(self, agent):
        if np.random.random() < self.epsilon:
            return np.random.choice(len(agent.value_estimates))
        else:
            action = np.argmax(agent.value_estimates)                    <---------
            check = np.where(agent.value_estimates == agent.value_estimates[action])[0]   <------
            if len(check) == 1:   <--- At least there is going to be 1 
                return action
            else:    <---- Ties are solved randomly
                return np.random.choice(check)
```

Please, let me know if I'm mistaking. Thank you!

**Comment by Naereen** [comment]
Hi @emiliocuestaf !
It's not my code (although I have written a much more complete bandit library, see https://github.com/SMPyBandits/SMPyBandits/), but I think you are completely right!
The first code does not make sense to me.

You can wait to have a feedback from the author @bgalbraith and then submit a pull request (see [this tutorial if needed](https://yangsu.github.io/pull-request-tutorial/)) to this project, maybe he will accept it (and it could fix this bug)!

**Comment by emiliocuestaf** [comment]
Ok, I see there  already was an issue talking about this bug. I'm sorry!
I think you should update the master branch

**Comment by Naereen** [comment]
Indeed, I didn't check but https://github.com/bgalbraith/bandits/issues/7

**Comment by bgalbraith** [comment]
hi @emiliocuestaf, you are correct. A few people have pointed this issue out and I didn't get around to merging in this fix (https://github.com/bgalbraith/bandits/pull/4). Thanks!
